version: "3.8"

services:
  db:
    image: postgres:15
    container_name: sis_postgres
    environment:
      POSTGRES_USER: sis_user
      POSTGRES_PASSWORD: sis_pass
      POSTGRES_DB: sis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sis_network

  app:
    build: .
    container_name: sis_app
    depends_on:
      - db
    networks:
      - sis_network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  sis_network:
